spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: userService
        uri: lb://userservice
        predicates:
        - Path=/api/auth/**,/api/account/**
      - id: tiltService
        uri: lb://tiltservice
        predicates:
        - Path=/api/tilt/**
eureka:
  instance:
    prefer-ip-address: true
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY