server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: frontendPublic
          uri: "http://localhost:8081"
          predicates:
            - Path=/**
