server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: userService
        uri: lb://userservice
        predicates:
        - Path=/api/auth/**,/api/account/**
      - id: tiltService
        uri: lb://tiltservice
        predicates:
        - Path=/api/tilt/**
      - id: frontendPublic
        uri: "http://localhost:8081"
        predicates:
        - Path=/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG