name: Build PeachPrivacy BackEnd
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Tilt-Service
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: tiltservice:bootBuildImage
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Build User-Service
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: userservice:bootBuildImage
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Build Gateway
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: gateway:bootBuildImage
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Build CloudConfig
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: cloudconfig:bootBuildImage
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
      - name: Google Artifact Registry Login
        uses: docker/login-action@v1
        with:
          registry: europe-west3-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      - name: Push Tilt-Serivce
        run: docker push europe-west3-docker.pkg.dev/peachprivacy/peachprivacy/tiltservice --all-tags
      - name: Push User-Serivce
        run: docker push europe-west3-docker.pkg.dev/peachprivacy/peachprivacy/userservice --all-tags
      - name: Push Gateway
        run: docker push europe-west3-docker.pkg.dev/peachprivacy/peachprivacy/gateway --all-tags
      - name: Push CloudConfig
        run: docker push europe-west3-docker.pkg.dev/peachprivacy/peachprivacy/cloudconfig --all-tags