name: Build PeachPrivacy FrontEnd
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Google Artifact Registry Login
        uses: docker/login-action@v1
        with:
          registry: europe-west3-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: frontend/
          push: true
          tags: europe-west3-docker.pkg.dev/peachprivacy/peachprivacy/frontend:latest
